'use client'; // This layout uses client-side hooks and event listeners

// Include imports for Lenis AND the cursor
import React, { useEffect, useRef, useState } from 'react';
import Lenis from '@studio-freight/lenis';
import { motion, useMotionValue, useSpring } from "framer-motion";
import Image from "next/image";
import GooeyNav from "@/blocks/Components/GooeyNav/GooeyNav";
import { usePathname } from 'next/navigation';
// Import the Link component from next/link
import Link from 'next/link';


import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { gilroy } from "@/fonts/fonts";

// Define items for GooeyNav (moved from page.tsx)
const items = [
  { label: "Home", href: "/" },
  { label: "About Me", href: "#about" },
  { label: "Experience", href: "#experience" },
  { label: "My Projects", href: "#projects" },
  { label: "Contact", href: "/Contact" },
];

// Define social media links and placeholder icon paths
const socialLinks = [
  { platform: "GitHub", href: "https://github.com/MelgibsonK", iconPath: "/icons/github_icon.svg" },
  { platform: "LinkedIn", href: "https://www.linkedin.com/in/melgibson-kennedy", iconPath: "/icons/linkedin_icon.svg" },
  { platform: "Gmail", href: "mailto:melgibsonkennedy@gmail.com", iconPath: "/icons/gmail_icon.svg" },
];


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// Metadata is for server components, so it stays outside the client component export
// It should ideally be in a separate metadata.ts file in App Router client components
// Keeping it commented out as in your provided code.
/*
  // app/metadata.ts
  import type { Metadata } from 'next';

  export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
  };
*/


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // State for mobile menu (moved from page.tsx)
  const [mobileMenuOpen, setMobileMenuOpen] = useState(false);
  // Get current pathname
  const pathname = usePathname();

  // Calculate active index based on pathname
  const activeIndex = items.findIndex(item => item.href === pathname);

  // --- Lenis Smooth Scrolling Implementation ---
  // Use useRef to hold the Lenis instance
  const lenis = useRef<Lenis | null>(null);

  useEffect(() => {
    // Initialize Lenis only in the browser environment
    if (typeof window !== 'undefined') {
      lenis.current = new Lenis({
        duration: 1.2, // Adjust the duration for scroll speed (seconds)
        easing: (t) => Math.min(1, 1.001 - Math.pow(2, -10 * t)), // Easing function (default lenis easing)
        smoothWheel: true, // Enable smooth scrolling for mouse wheel
        // wheelMultiplier: 1, // Adjust scroll speed sensitivity
        // touchMultiplier: 1,
        // infinite: false, // Set to true for infinite looping scrolling
        // autoResize: true, // Automatically handle window resizing
      });

      // This function updates Lenis on each frame using requestAnimationFrame
      function raf(time: number) {
        lenis.current?.raf(time);
        requestAnimationFrame(raf);
      }

      // Start the animation loop
      requestAnimationFrame(raf);

      // Clean up the Lenis instance when the component unmounts
      return () => {
        lenis.current?.destroy();
      };
    }
  }, []); // Empty dependency array ensures this effect runs only once on mount and cleans up on unmount
  // --- End Lenis Implementation ---


  // --- Custom Cursor Implementation (Moved from page.tsx) ---
  // Use MotionValues to track the raw mouse position
  // Initialize to 0 on both server and client to prevent hydration errors
  const cursorX = useMotionValue(0);
  const cursorY = useMotionValue(0);

  // Configure spring physics for the dot (follows closely)
  const dotSpringConfig = { damping: 25, stiffness: 200 };
  // Configure spring physics for the outline (trails the dot)
  const outlineSpringConfig = { damping: 35, stiffness: 400 }; // More damping/less stiffness for trailing

  // Create sprung motion values for the inner dot
  const dotX = useSpring(cursorX, dotSpringConfig);
  const dotY = useSpring(cursorY, dotSpringConfig);

  // Create sprung motion values for the outer outline, based on the dot's sprung values
  const outlineX = useSpring(dotX, outlineSpringConfig);
  const outlineY = useSpring(dotY, outlineSpringConfig);

  // Effect to update mouse position on mousemove AND set initial position after mount
  useEffect(() => {
    const moveCursor = (e: MouseEvent) => {
      cursorX.set(e.clientX);
      cursorY.set(e.clientY);
    };

    // Set initial cursor position to the center of the window after the component mounts
    // This runs only on the client after hydration
    // setTimeout is optional, but can help ensure initial positioning after paint
    setTimeout(() => {
        cursorX.set(window.innerWidth / 2);
        cursorY.set(window.innerHeight / 2);
    }, 0);


    // Add event listener for subsequent mouse movements
    window.addEventListener('mousemove', moveCursor);

    // Clean up event listener on component unmount
    return () => {
      window.removeEventListener('mousemove', moveCursor);
    };
  }, [cursorX, cursorY]); // Dependencies: update effect if motion values change (they won't here, but good practice)
  // --- End Custom Cursor Implementation ---


  return (
    <html lang="en">
      <body
        // Added bg-black class for black background
        className={`${geistSans.variable} ${geistMono.variable} ${gilroy.variable} antialiased font-gilroy bg-deep-charcoal`}
        style={{ cursor: 'none' }} // Apply cursor: none globally to the body
        >
        {/* Custom Cursor Dot */}
        <motion.div 
            style={{
            x: dotX, // Bind x position to the dot's sprung motion value
            y: dotY, // Bind y position to the dot's sprung motion value
            pointerEvents: 'none', // Ensure the cursor doesn't block clicks on elements below it
            left: 0, // Position relative to the viewport
            top: 0,
            position: 'fixed', // Stay in fixed position relative to the viewport
            zIndex: 9999, // Ensure it's always on top
            transform: 'translate(-50%, -50%)', // Center the div exactly on the cursor coordinates
            width: '8px', // Size of the inner dot
            height: '8px',
            borderRadius: '50%', // Make it round
            backgroundColor: '#B08D57', // Burnt Brass
            boxShadow: '0 0 10px 4px rgba(176, 141, 87, 0.7)', // Glowing effect
            }}
            className="hidden md:block" // Hide on mobile (optional, can be removed if you want it on mobile too)
        />
        {/* Custom Cursor Outline */}
        <motion.div
            style={{
            x: outlineX, // Bind x position to the outline's sprung motion value
            y: outlineY, // Bind y position to the outline's sprung motion value
            pointerEvents: 'none', // Ensure the cursor doesn't block clicks
            left: 0, // Position relative to the viewport
            top: 0,
            position: 'fixed', // Stay in fixed position
            zIndex: 9998, // Z-index slightly lower than the dot
            transform: 'translate(-50%, -50%)', // Center the div
            width: '30px', // Size of the outer circle
            height: '30px',
            borderRadius: '50%', // Make it round
            border: '2px solid #B08D57', // Burnt Brass border
            // Optional: opacity for transparency
            opacity: 0.5,
            }}
            className="hidden md:block" // Hide on mobile (optional, can be removed if you want it on mobile too)
        />
        {/* Header Section - Reduced height, no logo, better menu layout */}
        <header className="sticky top-0 z-50 flex w-full items-center justify-center px-4 py-2 md:px-6 md:py-2 bg-deep-charcoal/95 backdrop-blur-md border-b border-burnt-brass/30 h-14 md:h-16">
          {/* Desktop Navigation - Centered, full width */}
          <div className="hidden md:flex w-full max-w-6xl mx-auto items-center justify-center font-medium">
            <nav className="flex items-center gap-6 lg:gap-8">
              {items.map((item, index) => (
                <Link
                  key={index}
                  href={item.href}
                  className={`text-antique-linen/80 hover:text-burnt-brass px-3 py-2 text-sm lg:text-base font-medium transition-colors duration-200 border-b-2 border-transparent hover:border-burnt-brass ${
                    activeIndex === index ? 'text-burnt-brass border-burnt-brass' : ''
                  }`}
                >
                  {item.label}
                </Link>
              ))}
            </nav>
          </div>

          {/* Hamburger button - visible only on mobile, more visible */}
          <button
            className="md:hidden fixed top-3 right-4 z-50 p-2 focus:outline-none bg-deep-charcoal/90 rounded-md border border-burnt-brass/40"
            onClick={() => setMobileMenuOpen(!mobileMenuOpen)}
            aria-label="Toggle mobile menu"
          >
            {/* Hamburger icon lines with animation - more visible */}
            <div className={`w-6 h-0.5 bg-burnt-brass mb-1.5 transition-all duration-300 ease-in-out ${mobileMenuOpen ? 'rotate-45 translate-y-2' : ''}`}></div>
            <div className={`w-6 h-0.5 bg-burnt-brass mb-1.5 transition-all duration-300 ease-in-out ${mobileMenuOpen ? 'opacity-0' : ''}`}></div>
            <div className={`w-6 h-0.5 bg-burnt-brass transition-all duration-300 ease-in-out ${mobileMenuOpen ? '-rotate-45 -translate-y-2' : ''}`}></div>
          </button>
        </header>

        {/* Mobile menu - only visible when mobileMenuOpen is true */}
        {mobileMenuOpen && (
          <div className="md:hidden bg-deep-charcoal/98 backdrop-blur-lg border-t border-burnt-brass/40 fixed top-14 right-0 left-0 z-40 p-4 shadow-lg">
            <nav className="flex flex-col space-y-1">
              {items.map((item, index) => (
                <Link
                  key={index}
                  href={item.href}
                  className="text-antique-linen hover:text-burnt-brass py-3 px-4 font-medium text-base rounded-md hover:bg-burnt-brass/10 border-l-2 border-transparent hover:border-burnt-brass transition-all duration-200"
                  onClick={() => setMobileMenuOpen(false)}
                >
                  {item.label}
                </Link>
              ))}
            </nav>
          </div>
        )}
        {/* End Header Section */}

        {children} {/* This is where your page content (like page.tsx) will be rendered */}

        {/* Sticky Social Media Container */}
        {/* Redesigned with vintage theme */}
        <div className="fixed bottom-4 right-4 md:bottom-8 md:right-8 z-50 bg-deep-charcoal/80 border border-burnt-brass/40 border-dashed rounded-full p-2 md:p-4 flex flex-col items-center space-y-7 md:space-y-5 backdrop-blur-sm">
          {socialLinks.map((link) => (
            // Link for each social media icon
            <Link
              key={link.platform}
              href={link.href}
              target="_blank" // Open link in new tab
              rel="noopener noreferrer" // Security best practice for target="_blank"
              // Added hover effects
              className="transition-transform duration-200 hover:scale-110"
            >
              {/* Social media icon image */}
              <Image
                src={link.iconPath} // Use the icon path from the socialLinks array
                alt={`${link.platform} icon`}
                // Adjusted icon size responsively
                width={20} // Base size for mobile
                height={20} // Base size for mobile
                className="w-5 h-5 sm:w-6 sm:h-6 md:w-7 md:h-7 object-contain" // Responsive size and object-contain
              />
            </Link>
          ))}
        </div>
        {/* End Sticky Social Media Container */}

      </body>
    </html>
  );
}
