'use client';

import React, { useEffect, useRef, useState } from 'react';
import Lenis from '@studio-freight/lenis';
import Image from "next/image";
import { usePathname } from 'next/navigation';
import Link from 'next/link';


import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { gilroy } from "@/fonts/fonts";

// Define items for GooeyNav (moved from page.tsx)
const items = [
  { label: "Home", href: "/" },
  { label: "About Me", href: "#about" },
  { label: "Experience", href: "#experience" },
  { label: "My Projects", href: "#projects" },
  { label: "Resume", href: "/Resume" },
  { label: "Contact", href: "/Contact" },
];

// Define social media links and placeholder icon paths
const socialLinks = [
  { platform: "GitHub", href: "https://github.com/MelgibsonK", iconPath: "/icons/github_icon.svg" },
  { platform: "LinkedIn", href: "https://www.linkedin.com/in/melgibson-kennedy", iconPath: "/icons/linkedin_icon.svg" },
  { platform: "Gmail", href: "mailto:melgibsonkennedy@gmail.com", iconPath: "/icons/gmail_icon.svg" },
];


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// Metadata is for server components, so it stays outside the client component export
// It should ideally be in a separate metadata.ts file in App Router client components
// Keeping it commented out as in your provided code.
/*
  // app/metadata.ts
  import type { Metadata } from 'next';

  export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
  };
*/


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // State for mobile menu (moved from page.tsx)
  const [mobileMenuOpen, setMobileMenuOpen] = useState(false);
  // Get current pathname
  const pathname = usePathname();
  const [activeIndex, setActiveIndex] = useState(0);
  // State for scroll detection (desktop only)
  const [isScrolled, setIsScrolled] = useState(false);

  // Calculate active index based on pathname and hash
  useEffect(() => {
    const updateActiveIndex = () => {
      if (typeof window === 'undefined') return;
      
      const currentHash = window.location.hash;
      const currentPath = window.location.pathname;
      
      // Check for hash links first (for sections on home page)
      if (currentHash) {
        const hashIndex = items.findIndex(item => item.href === currentHash);
        if (hashIndex !== -1) {
          setActiveIndex(hashIndex);
          return;
        }
      }
      
      // Check for exact pathname match (for Contact page)
      const pathIndex = items.findIndex(item => item.href === currentPath);
      if (pathIndex !== -1) {
        setActiveIndex(pathIndex);
        return;
      }
      
      // Default to Home (index 0) if on root path
      if (currentPath === '/' || currentPath === '') {
        setActiveIndex(0);
        return;
      }
    };

    // Initial update
    updateActiveIndex();

    // Listen for hash changes (when clicking nav links)
    const handleHashChange = () => {
      updateActiveIndex();
    };

    window.addEventListener('hashchange', handleHashChange);
    
    // Also check on scroll to update active section (for home page sections)
    const handleScroll = () => {
      // Check if scrolled (desktop only - for floating pill effect)
      if (window.innerWidth >= 768) {
        setIsScrolled(window.scrollY > 50);
      }
      
      if (pathname === '/') {
        const sections = ['#about', '#experience', '#projects'];
        const scrollPosition = window.scrollY + 200; // Offset for header
        
        for (let i = sections.length - 1; i >= 0; i--) {
          const element = document.querySelector(sections[i]);
          if (element) {
            const elementTop = (element as HTMLElement).offsetTop;
            if (scrollPosition >= elementTop) {
              const sectionIndex = items.findIndex(item => item.href === sections[i]);
              if (sectionIndex !== -1) {
                setActiveIndex(sectionIndex);
                return;
              }
            }
          }
        }
        // If at top of page, show Home as active
        if (scrollPosition < 300) {
          setActiveIndex(0);
        }
      }
    };

    // Throttle scroll events for performance
    let ticking = false;
    const throttledScroll = () => {
      if (!ticking) {
        window.requestAnimationFrame(() => {
          handleScroll();
          ticking = false;
        });
        ticking = true;
      }
    };

    window.addEventListener('scroll', throttledScroll, { passive: true });
    
    // Handle window resize - reset scroll state if switching to mobile
    const handleResize = () => {
      if (window.innerWidth < 768) {
        setIsScrolled(false);
      }
    };
    
    window.addEventListener('resize', handleResize);
    
    return () => {
      window.removeEventListener('hashchange', handleHashChange);
      window.removeEventListener('scroll', throttledScroll);
      window.removeEventListener('resize', handleResize);
    };
  }, [pathname]);

  // --- Lenis Smooth Scrolling Implementation ---
  // Use useRef to hold the Lenis instance
  const lenis = useRef<Lenis | null>(null);

  useEffect(() => {
    // Initialize Lenis only in the browser environment
    if (typeof window !== 'undefined') {
      lenis.current = new Lenis({
        duration: 1.2, // Adjust the duration for scroll speed (seconds)
        easing: (t) => Math.min(1, 1.001 - Math.pow(2, -10 * t)), // Easing function (default lenis easing)
        smoothWheel: true, // Enable smooth scrolling for mouse wheel
        // wheelMultiplier: 1, // Adjust scroll speed sensitivity
        // touchMultiplier: 1,
        // infinite: false, // Set to true for infinite looping scrolling
        // autoResize: true, // Automatically handle window resizing
      });

      // This function updates Lenis on each frame using requestAnimationFrame
      function raf(time: number) {
        lenis.current?.raf(time);
        requestAnimationFrame(raf);
      }

      // Start the animation loop
      requestAnimationFrame(raf);

      // Clean up the Lenis instance when the component unmounts
      return () => {
        lenis.current?.destroy();
      };
    }
  }, []); // Empty dependency array ensures this effect runs only once on mount and cleans up on unmount
  // --- End Lenis Implementation ---


  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${gilroy.variable} antialiased font-gilroy bg-deep-charcoal`}
        >
        {/* Header Section - Transparent overlay on background image, floating pill when scrolled (desktop) */}
        <header 
          className={`sticky z-50 flex items-center justify-center transition-all duration-300 ${
            isScrolled 
              ? 'md:top-4 md:left-16 md:right-16 md:rounded-full md:px-6 md:py-2 md:bg-black/30 md:backdrop-blur-lg md:shadow-2xl md:w-fit md:mx-auto' 
              : 'top-0 w-full px-4 py-2 md:px-6 md:py-2 bg-deep-charcoal/30 backdrop-blur-md'
          } h-14 md:h-16`}
        >
          {/* Desktop Navigation - Centered, maintains same layout */}
          <div className="hidden md:flex items-center justify-center font-medium">
            <nav className="flex items-center gap-6 lg:gap-8">
              {items.map((item, index) => {
                const isActive = activeIndex === index;
                return (
                  <Link
                    key={index}
                    href={item.href}
                    className={`relative px-3 py-2 text-base lg:text-lg font-bold transition-all duration-300 ${
                      isActive 
                        ? 'text-mist-gray' 
                        : 'text-antique-linen/80 hover:text-burnt-brass'
                    }`}
                  >
                    {item.label}
                    {/* Extended circle with rounded corners for active item */}
                    {isActive && (
                      <span 
                        className="absolute bottom-0 left-1/2 -translate-x-1/2 h-1.5 rounded-full"
            style={{
                          width: 'calc(100% + 16px)',
                          backgroundColor: '#D9D9D6',
                          boxShadow: '0 0 10px rgba(176, 141, 87, 0.8)'
                        }}
                      ></span>
                    )}
                    {/* Hover underline effect for non-active items */}
                    {!isActive && (
                      <span className="absolute bottom-0 left-0 right-0 h-0.5 bg-burnt-brass/50 opacity-0 hover:opacity-100 scale-x-0 hover:scale-x-100 transition-all duration-300 origin-left"></span>
                    )}
            </Link>
                );
              })}
            </nav>
          </div>

          {/* Hamburger button - visible only on mobile, more visible */}
          <button
            className="md:hidden fixed top-2.5 right-3 z-[60] p-1.5 focus:outline-none bg-soft-white rounded-md border border-deep-charcoal shadow-lg"
            onClick={() => setMobileMenuOpen(!mobileMenuOpen)}
            aria-label="Toggle mobile menu"
            style={{ backgroundColor: '#FAF9F6' }}
          >
            {/* Hamburger icon lines with animation - dark for visibility */}
            <div className={`w-5 h-0.5 bg-deep-charcoal mb-1.5 transition-all duration-300 ease-in-out rounded ${mobileMenuOpen ? 'rotate-45 translate-y-2' : ''}`} style={{ backgroundColor: '#1F1F1C' }}></div>
            <div className={`w-5 h-0.5 bg-deep-charcoal mb-1.5 transition-all duration-300 ease-in-out rounded ${mobileMenuOpen ? 'opacity-0' : ''}`} style={{ backgroundColor: '#1F1F1C' }}></div>
            <div className={`w-5 h-0.5 bg-deep-charcoal transition-all duration-300 ease-in-out rounded ${mobileMenuOpen ? '-rotate-45 -translate-y-2' : ''}`} style={{ backgroundColor: '#1F1F1C' }}></div>
          </button>
        </header>

        {/* Mobile menu - only visible when mobileMenuOpen is true */}
        {mobileMenuOpen && (
          <div className="md:hidden bg-deep-charcoal/98 backdrop-blur-lg border-t border-burnt-brass/40 fixed top-14 right-0 left-0 z-40 p-4 shadow-lg">
            <nav className="flex flex-col space-y-1">
              {items.map((item, index) => {
                const isActive = activeIndex === index;
                return (
                <Link
                  key={index}
                  href={item.href}
                    className={`relative py-3 px-4 font-bold text-lg rounded-md transition-all duration-300 ${
                      isActive
                        ? 'text-mist-gray'
                        : 'text-antique-linen hover:text-burnt-brass border-transparent hover:border-burnt-brass/50 hover:bg-burnt-brass/10'
                    }`}
                    onClick={() => setMobileMenuOpen(false)}
                >
                  {item.label}
                    {/* Extended circle with rounded corners for active item */}
                    {isActive && (
                      <span 
                        className="absolute left-1/2 top-1/2 -translate-x-1/2 -translate-y-1/2 rounded-full"
                        style={{
                          width: 'calc(100% - 16px)',
                          height: 'calc(100% - 8px)',
                          backgroundColor: 'rgba(217, 217, 214, 0.15)',
                          border: '2px solid #D9D9D6',
                          boxShadow: '0 0 10px rgba(176, 141, 87, 0.8)'
                        }}
                      ></span>
                    )}
                </Link>
                );
              })}
            </nav>
          </div>
        )}
        {/* End Header Section */}

        {children} {/* This is where your page content (like page.tsx) will be rendered */}

        {/* Sticky Social Media Container */}
        {/* Redesigned with vintage theme - matching detached header style */}
        <div className="fixed bottom-4 right-4 md:bottom-8 md:right-8 z-50 bg-black/30 border border-burnt-brass/40 border-dashed rounded-full p-2 md:p-4 flex flex-col items-center space-y-7 md:space-y-5 backdrop-blur-lg">
          {socialLinks.map((link) => (
            // Link for each social media icon
            <Link
              key={link.platform}
              href={link.href}
              target="_blank" // Open link in new tab
              rel="noopener noreferrer" // Security best practice for target="_blank"
              // Added hover effects
              className="transition-transform duration-200 hover:scale-110"
            >
              {/* Social media icon image */}
              <Image
                src={link.iconPath} // Use the icon path from the socialLinks array
                alt={`${link.platform} icon`}
                // Adjusted icon size responsively
                width={20} // Base size for mobile
                height={20} // Base size for mobile
                className="w-5 h-5 sm:w-6 sm:h-6 md:w-7 md:h-7 object-contain" // Responsive size and object-contain
              />
            </Link>
          ))}
          {/* Resume Download Icon */}
          <button
            onClick={() => {
              const link = document.createElement('a');
              link.href = '/files/melgibsone.pdf';
              link.download = 'Resume-Melgibson_Kennedy_Odari.pdf';
              document.body.appendChild(link);
              link.click();
              document.body.removeChild(link);
            }}
            className="transition-transform duration-200 hover:scale-110"
            aria-label="Download Resume"
          >
            <Image
              src="/icons/resume-portfolio-svgrepo-com.svg"
              alt="Resume icon"
              width={20}
              height={20}
              className="w-5 h-5 sm:w-6 sm:h-6 md:w-7 md:h-7 object-contain filter brightness-0 invert"
            />
          </button>
        </div>
        {/* End Sticky Social Media Container */}

      </body>
    </html>
  );
}
